services:
    storage:
        image: redis
        volumes:
            - ./data:/data
    lib:
        image: pigrov/lib:v1.6
        ports:
            - 80:3003
        environment:
            - PORT=3003
            - REDIS_URL=redis://storage
            - MONGO_URL=mongodb://localhost:27017/mydb
        depends_on:
            - storage
    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
            ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
