services:
    storage:
        image: redis
        volumes:
            - ./data:/data

    lib:
        image: pigrov/lib:v1.6
        ports:
            - 80:3003
        environment:
            - PORT=3003
            - REDIS_URL=redis://storage
        depends_on:
            - storage
